### ISSUE TITLE
ステージ落下時における操作不能状態

### ISSUE THREAD

**Issue by keika299** [HassakuTb/KiritanAction#1]
## 問題点
きりたんがステージの端から落下すると、延々と落ち続け
操作不能の状態に陥ってしまう。

## 確認環境
Google Chrome 52

## 期待する処理
本来であれば死亡処理などが入りそうですが、
ひとまずの所Z軸が規定未満の時にスタート地点に戻るだけでもよいかと思います。
もしくは、特定のキーでステージをリセットする等でもいけそうです。

**Comment by HassakuTb** [comment]
報告ありがとうございます。

# 対応

ステージ限界の衝突判定を追加します。
最終的には死亡処理を実装しますが、ひとまずはステージの限界に到達するとスタート地点に戻るように実装します。

**Comment by HassakuTb** [comment]
#2 にて対応プルリクエストを作成したためCloseします。

**Comment by HassakuTb** [comment]
#2 にて解消・ビルドしたのでクローズしました。

**Comment by keika299** [comment]
対応ありがとうございます！😄
