### ISSUE TITLE
壁キャノン（壁キック）の実装

### ISSUE THREAD

**Issue by HassakuTb** [HassakuTb/KiritanAction#33]
Lv2用のアクションとして実装する
* 壁際でz or 壁方向+z

**Comment by keika299** [comment]
壁キックはどのような場面で使用されるイメージですかね？
勝手な想像ですが、あまりきりたんは俊敏なイメージではないので、反重力ジャンプもあるしであまり必要でもないかと思ってます。

**Comment by HassakuTb** [comment]
まあきりたんは俊敏ではないですよね。想定しているのは壁キックというより壁キャノンですかね。
プレイヤーの行動範囲を増やすのが目的です。砲撃の反動利用では縦方向のスピードを確保できないので「Lv2でないと到達できないエリア」が作りやすくなります。（反重力ジャンプは少なくとも永久に上昇できるようにはしない予定です）
加えて上手なプレイヤーに壁にぶつかった時にとりあえず出す「繋ぎのアクション」を提供します。
壁にぶつかったら横方向の移動が止まるのですが、それまでの進行方向+zで簡単に逆方向に移動させることでストレスを感じにくくなります。（ある程度以上の速度で壁にぶつかった時に反動での跳ね返りがあるなら必要ないかもしれませんね）

**Comment by keika299** [comment]
なるほど、そうなるとよりアクション性が増す感じですね。
実際、どういう入力で壁キックを発生させるかは考えどころですね。
もしくは特殊な壁に高速でぶつかった時だけ跳ね返りを発生させるというのも面白いかなと、思いつきレベルですが加えておきます。

**Comment by HassakuTb** [comment]
入力は壁際かつ空中でzまたは壁方向+zを推しておきます。
注意すべきは壁キックの後ですね。
キックの後一瞬空中横入力による制御をできなくすると連続壁キック等の操作がしやすくなります。
逆に連続キックで壁を登るアクション（ロックマンXの壁登りのような）を許可するなら直後から操作できる必要があります。
ここをどうするかは要検討だと思っています。

**Comment by HassakuTb** [comment]
* 壁キック後、壁キック状態へ移行。
* 壁キック状態では壁キックと空中ダッシュが可能。それ以外は無効。
* 0.5秒(25フレ)経過で通常状態に移行。
