### ISSUE TITLE
空中ダッシュの実装

### ISSUE THREAD

**Issue by HassakuTb** [HassakuTb/KiritanAction#34]
Lv2アクションとして実装する
* Z + 横

### 確認項目
* [ ] 簡単に出すことができる
* [ ] Lv1のときに出せない

**Comment by keika299** [comment]
イメージとしては反重力ジャンプを横に出す感じですかね？

**Comment by HassakuTb** [comment]
Lv1では越せない溝を飛び越えさせてプレイヤーの行動範囲を増やすのと、
素の横移動の遅さのストレスを解消させるのが目的です。
初心者でも簡単に扱える必要があります。

反重力ジャンプは速度を加える実装してますが空中ダッシュは縦方向の速度を0にしたいと思っています。
より直感的で素直な挙動です。（反重力ジャンプの方もこの方式でもいいかと思ってますが）
押しっぱなしの間は縦方向の速度を0のまま維持するとかでもいいかもしれません。

**Comment by keika299** [comment]
なるほど、理解しました。
そうすると、
- 横キー2連打
- 他キーをおしながら横キー入力
の2パターンが考えられますが、どちらがいいですかね？
他キーだと、z + up で反重力なんで、z併用が直感的ですかね？

**Comment by HassakuTb** [comment]
横入力+zが入力簡単で直感的かと。長押しを使うならどっちか長押しですね。
2連打は出るまでに絶対にラグができてしまうのでストレスたまりやすいですし、指が疲れやすいのでオススメできないです。

**Comment by keika299** [comment]
2連打は確かに疲れやすいという点があるのですが、私感では2Dのゲームでは採用されていることが多いように感じたので、ユーザーが慣れているかなとも思います。（私が最初にこのゲームを触らせてもらった時に連打でダッシュを出そうとしたので）
なんにせよ、上方向の操作がすでにあるので、それの横版と考えれば抵抗なく受け入れてもらえそうですね。

 z＋横キーでいきましょう。

**Comment by ProjectTomo** [comment]
こんにちは

**Comment by keika299** [comment]
すみません気づいてませんでした :sob:

**Comment by HassakuTb** [comment]
#41 で戴いたPRとは随分違うものになってしまいました :bow: #54
