### ISSUE TITLE
gitter 導入提案

### ISSUE THREAD

**Issue by keika299** [HassakuTb/KiritanAction#6]
私ばっかり色々言って恐縮ですがー･･･

可能であればgitterを導入してコミュニケーションしやすいようにしてみたらどうでしょうか。

Hassaku さんがそこまでするほどでも･･･って感じでしたらこのままの進行でもいいですけど、
チャットベースの方がコミュニケーションとりやすいと思うんですよね！:+1:

**Comment by HassakuTb** [comment]
毎度提案ありがとうございます！
早速導入してみました。

**Comment by keika299** [comment]
ありがとうございます！
